/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package task4;

import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

public class AddWord extends javax.swing.JFrame {

    /**
     * Creates new form AddWord
     */
    public AddWord() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        CloseLabel = new javax.swing.JLabel();
        MinusLabel = new javax.swing.JLabel();
        Dictionary = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        SearchTextField = new javax.swing.JTextField();
        Difinition_Label = new javax.swing.JLabel();
        DifTextField = new javax.swing.JTextField();
        SahmLabel = new javax.swing.JLabel();
        LanguageLabel = new javax.swing.JLabel();
        voicLabel = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        backLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        HeaderPanel.setBackground(new java.awt.Color(56, 81, 93));

        CloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLabel.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Xbox X_30px_1.png")); // NOI18N
        CloseLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseLabelMouseExited(evt);
            }
        });

        MinusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinusLabel.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Minus_30px_1.png")); // NOI18N
        MinusLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinusLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinusLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinusLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinusLabelMouseExited(evt);
            }
        });

        Dictionary.setFont(new java.awt.Font("Consolas", 3, 30)); // NOI18N
        Dictionary.setForeground(new java.awt.Color(2, 50, 42));
        Dictionary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dictionary.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Google Translate_50px.png")); // NOI18N
        Dictionary.setText("Dictionary");
        Dictionary.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addComponent(Dictionary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 945, Short.MAX_VALUE)
                .addComponent(MinusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CloseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CloseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MinusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Dictionary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        MainPanel.setBackground(new java.awt.Color(47, 70, 81));

        SearchTextField.setBackground(new java.awt.Color(47, 70, 81));
        SearchTextField.setFont(new java.awt.Font("Monospaced", 3, 30)); // NOI18N
        SearchTextField.setForeground(new java.awt.Color(2, 28, 28));
        SearchTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 236), 2, true));

        Difinition_Label.setFont(new java.awt.Font("Consolas", 3, 30)); // NOI18N
        Difinition_Label.setForeground(new java.awt.Color(2, 35, 29));
        Difinition_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Difinition_Label.setText("Definition");
        Difinition_Label.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(78, 52, 46), 2, true));

        DifTextField.setBackground(new java.awt.Color(47, 70, 81));
        DifTextField.setFont(new java.awt.Font("Monospaced", 3, 30)); // NOI18N
        DifTextField.setForeground(new java.awt.Color(2, 28, 28));
        DifTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DifTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 236), 2, true));

        SahmLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SahmLabel.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Logout Rounded Down_25px.png")); // NOI18N

        LanguageLabel.setFont(new java.awt.Font("Consolas", 3, 30)); // NOI18N
        LanguageLabel.setForeground(new java.awt.Color(0, 43, 43));
        LanguageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LanguageLabel.setText("EN->AR");
        LanguageLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(78, 52, 46), 2, true));

        voicLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voicLabel.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Microphone_50px_1.png")); // NOI18N
        voicLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(78, 52, 46), 2, true));
        voicLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voicLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voicLabelMouseClicked(evt);
            }
        });

        AddButton.setBackground(new java.awt.Color(41, 56, 64));
        AddButton.setFont(new java.awt.Font("Consolas", 3, 30)); // NOI18N
        AddButton.setForeground(new java.awt.Color(2, 35, 29));
        AddButton.setText("Add");
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddButtonMouseExited(evt);
            }
        });

        backLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLabel.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Reply Arrow_100px.png")); // NOI18N
        backLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(147, 144, 173), 2, true));
        backLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(LanguageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(voicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                    .addComponent(Difinition_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(523, 523, 523))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                    .addComponent(SahmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(516, 516, 516)))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(DifTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(259, 259, 259))))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(backLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(voicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(LanguageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(32, 32, 32)
                .addComponent(Difinition_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SahmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(DifTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(backLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void CloseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseEntered
        CloseLabel.setBackground(Color.RED);
        CloseLabel.setOpaque(true);
    }//GEN-LAST:event_CloseLabelMouseEntered

    private void CloseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseExited
        CloseLabel.setBackground(null);
        CloseLabel.setOpaque(false);
    }//GEN-LAST:event_CloseLabelMouseExited

    private void MinusLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabelMouseClicked
        this.setState(DictionaryProject.ICONIFIED);
    }//GEN-LAST:event_MinusLabelMouseClicked

    private void MinusLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabelMouseEntered
        MinusLabel.setBackground(Color.LIGHT_GRAY);
        MinusLabel.setOpaque(true);
    }//GEN-LAST:event_MinusLabelMouseEntered

    private void MinusLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabelMouseExited
        MinusLabel.setBackground(null);
        MinusLabel.setOpaque(false);
    }//GEN-LAST:event_MinusLabelMouseExited

    private void AddButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseEntered
        AddButton.setBackground(Color.DARK_GRAY);
        AddButton.setOpaque(true);
    }//GEN-LAST:event_AddButtonMouseEntered

    private void AddButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseExited
         AddButton.setBackground(null);
        AddButton.setOpaque(false);
    }//GEN-LAST:event_AddButtonMouseExited

    private void AddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseClicked
        File f1 = new File("EnglishWords.txt");
        File f2 = new File("ArabicWords.txt");
        BufferedWriter bw1 = null;
        BufferedWriter BW2 = null;
        try {
            FileWriter fw1 = new FileWriter(f1 , true);
            FileWriter fw2 = new FileWriter(f2 , true);
             bw1 = new BufferedWriter(fw1);
             BW2  = new BufferedWriter(fw2);
            bw1.write(SearchTextField.getText());
            bw1.newLine();
            BW2.write(DifTextField.getText());
            BW2.newLine();
           JOptionPane.showMessageDialog(null, "Successfully added ^__^");
           SearchTextField.setText("");
           DifTextField.setText("");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, " ooh --> ERROR ^-_-^");
        }finally{
            try {
                bw1.close();
                BW2.close();
            } catch (Exception e) {
            }
            
        }
    }//GEN-LAST:event_AddButtonMouseClicked

    private void backLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseEntered
        backLabel.setBackground(new Color(109, 76, 65));
        backLabel.setOpaque(true);
        Border b = BorderFactory.createLineBorder(new Color(147, 144,17), 2, true);
        backLabel.setBorder(b);
    }//GEN-LAST:event_backLabelMouseEntered

    private void backLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseExited
        backLabel.setBackground(null);
        backLabel.setOpaque(false);
        Border b = BorderFactory.createLineBorder(new Color(147, 144,173), 2, true);
        backLabel.setBorder(b);
    }//GEN-LAST:event_backLabelMouseExited

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        DictionaryProject dic = new DictionaryProject();
        dic.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backLabelMouseClicked

    private void voicLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voicLabelMouseClicked
        VoiceManager vm = VoiceManager.getInstance();
        Voice v = vm.getVoice("kevin16");
        v.allocate();
        v.speak(SearchTextField.getText());
    }//GEN-LAST:event_voicLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddWord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JLabel Dictionary;
    private javax.swing.JTextField DifTextField;
    private javax.swing.JLabel Difinition_Label;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel LanguageLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel MinusLabel;
    private javax.swing.JLabel SahmLabel;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel voicLabel;
    // End of variables declaration//GEN-END:variables
}
