/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package task4;

import java.awt.Color;
import java.io.File;
import java.nio.file.Files;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author AhmedTalal
 */
public class CopyFile extends javax.swing.JFrame {

    /**
     * Creates new form CopyFile
     */
    public CopyFile() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        CloseLabel = new javax.swing.JLabel();
        MinusLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        FilePath = new javax.swing.JTextField();
        OriginalLabel = new javax.swing.JLabel();
        copyButton = new javax.swing.JButton();
        newLabel = new javax.swing.JLabel();
        FileNmewPath = new javax.swing.JTextField();
        CutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        headerPanel.setBackground(new java.awt.Color(136, 14, 79));

        CloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLabel.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Xbox X_30px_1.png")); // NOI18N
        CloseLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseLabelMouseExited(evt);
            }
        });

        MinusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinusLabel.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Minus_30px_1.png")); // NOI18N
        MinusLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinusLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinusLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinusLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinusLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MinusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(CloseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MinusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(CloseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(236, 64, 122));

        FilePath.setBackground(new java.awt.Color(236, 64, 122));
        FilePath.setFont(new java.awt.Font("Segoe Print", 3, 20)); // NOI18N
        FilePath.setForeground(new java.awt.Color(121, 85, 72));
        FilePath.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(173, 20, 87), 4, true));

        OriginalLabel.setFont(new java.awt.Font("Segoe Print", 3, 20)); // NOI18N
        OriginalLabel.setForeground(new java.awt.Color(121, 85, 72));
        OriginalLabel.setText("Enter the Original path : ");

        copyButton.setBackground(new java.awt.Color(236, 64, 122));
        copyButton.setFont(new java.awt.Font("Segoe Print", 3, 22)); // NOI18N
        copyButton.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Copy_70px.png")); // NOI18N
        copyButton.setText("Copy");
        copyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        copyButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        copyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                copyButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                copyButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                copyButtonMouseExited(evt);
            }
        });
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });

        newLabel.setFont(new java.awt.Font("Segoe Print", 3, 20)); // NOI18N
        newLabel.setForeground(new java.awt.Color(121, 85, 72));
        newLabel.setText("Enter the new path : ");

        FileNmewPath.setBackground(new java.awt.Color(236, 64, 122));
        FileNmewPath.setFont(new java.awt.Font("Segoe Print", 3, 20)); // NOI18N
        FileNmewPath.setForeground(new java.awt.Color(121, 85, 72));
        FileNmewPath.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(173, 20, 87), 4, true));

        CutButton.setBackground(new java.awt.Color(236, 64, 122));
        CutButton.setFont(new java.awt.Font("Segoe Print", 3, 22)); // NOI18N
        CutButton.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Cut_70px.png")); // NOI18N
        CutButton.setText("Cut");
        CutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CutButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        CutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CutButtonMouseExited(evt);
            }
        });
        CutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OriginalLabel)
                            .addComponent(newLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FilePath, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                            .addComponent(FileNmewPath)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(466, 466, 466)
                        .addComponent(copyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(CutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OriginalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FileNmewPath, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(copyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void CloseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseEntered
        CloseLabel.setBackground(Color.RED);
        CloseLabel.setOpaque(true);
    }//GEN-LAST:event_CloseLabelMouseEntered

    private void CloseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseExited
       CloseLabel.setBackground(null);
       CloseLabel.setOpaque(false);
    }//GEN-LAST:event_CloseLabelMouseExited

    private void MinusLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabelMouseClicked
        this.setState(CopyFile.ICONIFIED);
    }//GEN-LAST:event_MinusLabelMouseClicked

    private void MinusLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabelMouseEntered
        MinusLabel.setBackground(Color.GRAY);
        MinusLabel.setOpaque(true);
    }//GEN-LAST:event_MinusLabelMouseEntered

    private void MinusLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabelMouseExited
        MinusLabel.setBackground(null);
        MinusLabel.setOpaque(false);
    }//GEN-LAST:event_MinusLabelMouseExited

    private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copyButtonActionPerformed

    private void CutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CutButtonActionPerformed

    private void copyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyButtonMouseClicked
       if(FilePath.getText().equals("")  & FileNmewPath.getText().equals(""))
       {
           JOptionPane.showMessageDialog(null," Please : Enter the original file path and new file path ", "Messege", 3);
       }else
       {
           File originalFile = new File(FilePath.getText());
        File newFile =  new File(FileNmewPath.getText());
        try {
            Files.copy(originalFile.toPath(), newFile.toPath());
            JOptionPane.showMessageDialog(null, "Copy completed successfully" , "Messege" , 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage() , "Error" , 1);
        }
       }
        
    }//GEN-LAST:event_copyButtonMouseClicked

    private void copyButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyButtonMouseEntered
       copyButton.setBackground(Color.GRAY);
       copyButton.setOpaque(true);
        javax.swing.border.Border b  = BorderFactory.createLineBorder(Color.GRAY, 3, true);
       copyButton.setBorder(b);
    }//GEN-LAST:event_copyButtonMouseEntered

    private void copyButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyButtonMouseExited
        copyButton.setBackground(null);
        copyButton.setOpaque(false);
        copyButton.setBorder(null);
    }//GEN-LAST:event_copyButtonMouseExited

    private void CutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CutButtonMouseClicked
        if(FilePath.getText().equals("")  & FileNmewPath.getText().equals(""))
       {
           JOptionPane.showMessageDialog(null," Please : Enter the original file path and new file path ", "Messege", 3);
       }else
       {
           File originalFile = new File(FilePath.getText());
        File newFile =  new File(FileNmewPath.getText());
        try {
            Files.move(originalFile.toPath(), newFile.toPath());
            JOptionPane.showMessageDialog(null, "cut completed successfully" , "Messege" , 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage() , "Error" , 1);
        }
       } 
    }//GEN-LAST:event_CutButtonMouseClicked

    private void CutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CutButtonMouseEntered
        CutButton.setBackground(Color.GRAY);
        CutButton.setOpaque(true);
         javax.swing.border.Border b =  BorderFactory.createLineBorder(Color.GRAY, 3, true);
         CutButton.setBorder(b);
    }//GEN-LAST:event_CutButtonMouseEntered

    private void CutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CutButtonMouseExited
        CutButton.setBackground(null);
        CutButton.setOpaque(false);
        CutButton.setBorder(null);
    }//GEN-LAST:event_CutButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CopyFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CopyFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CopyFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CopyFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        CopyFile c = new CopyFile();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                c.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JButton CutButton;
    private javax.swing.JTextField FileNmewPath;
    private javax.swing.JTextField FilePath;
    private javax.swing.JLabel MinusLabel;
    private javax.swing.JLabel OriginalLabel;
    private javax.swing.JButton copyButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel newLabel;
    // End of variables declaration//GEN-END:variables
}
