/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package task4;

import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.plaf.IconUIResource;

/**
 *
 * @author AhmedTalal
 */
public class DictionaryProject extends javax.swing.JFrame {
    
    String result = null;
    ArrayList< String> list = new ArrayList<>();
    boolean check = false;
    public DictionaryProject() {
        initComponents();
        this.setLocationRelativeTo(null);
        ModifyButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        CloseLabel = new javax.swing.JLabel();
        MinusLabel = new javax.swing.JLabel();
        Dictionary = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        SearchTextField = new javax.swing.JTextField();
        TranslateButton = new javax.swing.JButton();
        Difinition_Label = new javax.swing.JLabel();
        SahmLabel = new javax.swing.JLabel();
        LanguageLabel = new javax.swing.JLabel();
        voicLabel = new javax.swing.JLabel();
        ListButton = new javax.swing.JButton();
        LeftScrollPane = new javax.swing.JScrollPane();
        LeftPanel = new javax.swing.JPanel();
        AddLabel = new javax.swing.JLabel();
        ConvertLanhuage = new javax.swing.JLabel();
        ModifyLabel = new javax.swing.JLabel();
        DifTextField = new javax.swing.JTextField();
        FilterButton = new javax.swing.JButton();
        ModifyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);

        HeaderPanel.setBackground(new java.awt.Color(53, 87, 103));

        CloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseLabelMouseExited(evt);
            }
        });

        MinusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinusLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinusLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinusLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinusLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinusLabelMouseExited(evt);
            }
        });

        Dictionary.setFont(new java.awt.Font("Consolas", 3, 30)); // NOI18N
        Dictionary.setForeground(new java.awt.Color(2, 52, 44));
        Dictionary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dictionary.setText("Dictionary");
        Dictionary.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addComponent(Dictionary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CloseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CloseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MinusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Dictionary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        MainPanel.setBackground(new java.awt.Color(56, 81, 93));

        SearchTextField.setBackground(new java.awt.Color(47, 70, 81));
        SearchTextField.setFont(new java.awt.Font("Monospaced", 3, 30)); // NOI18N
        SearchTextField.setForeground(new java.awt.Color(2, 28, 28));
        SearchTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 236), 2, true));

        TranslateButton.setBackground(new java.awt.Color(41, 56, 64));
        TranslateButton.setFont(new java.awt.Font("Consolas", 3, 30)); // NOI18N
        TranslateButton.setForeground(new java.awt.Color(2, 35, 29));
        TranslateButton.setText("translate");
        TranslateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TranslateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TranslateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TranslateButtonMouseExited(evt);
            }
        });
        TranslateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TranslateButtonActionPerformed(evt);
            }
        });

        Difinition_Label.setFont(new java.awt.Font("Consolas", 3, 30)); // NOI18N
        Difinition_Label.setForeground(new java.awt.Color(2, 35, 29));
        Difinition_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Difinition_Label.setText("Definition");
        Difinition_Label.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(78, 52, 46), 2, true));

        SahmLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        LanguageLabel.setFont(new java.awt.Font("Consolas", 3, 30)); // NOI18N
        LanguageLabel.setForeground(new java.awt.Color(0, 40, 40));
        LanguageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LanguageLabel.setText("EN->AR");
        LanguageLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(78, 52, 46), 2, true));

        voicLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voicLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(78, 52, 46), 2, true));
        voicLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voicLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voicLabelMouseClicked(evt);
            }
        });

        ListButton.setBackground(new java.awt.Color(5, 59, 59));
        ListButton.setForeground(new java.awt.Color(52, 75, 87));
        ListButton.setBorder(null);
        ListButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListButton.setFocusPainted(false);
        ListButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ListButtonMouseEntered(evt);
            }
        });
        ListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListButtonActionPerformed(evt);
            }
        });

        LeftScrollPane.setBackground(new java.awt.Color(121, 85, 72));
        LeftScrollPane.setBorder(null);
        LeftScrollPane.setForeground(new java.awt.Color(121, 85, 72));
        LeftScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        LeftScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        LeftPanel.setBackground(new java.awt.Color(93, 115, 126));
        LeftPanel.setForeground(new java.awt.Color(93, 115, 126));

        AddLabel.setBackground(new java.awt.Color(53, 56, 59));
        AddLabel.setFont(new java.awt.Font("Consolas", 3, 32)); // NOI18N
        AddLabel.setForeground(new java.awt.Color(0, 66, 55));
        AddLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddLabel.setText("add");
        AddLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(121, 85, 72), 2, true));
        AddLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        AddLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddLabelMouseExited(evt);
            }
        });

        ConvertLanhuage.setBackground(new java.awt.Color(53, 56, 59));
        ConvertLanhuage.setFont(new java.awt.Font("Consolas", 3, 32)); // NOI18N
        ConvertLanhuage.setForeground(new java.awt.Color(0, 66, 55));
        ConvertLanhuage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ConvertLanhuage.setText("AR->EN");
        ConvertLanhuage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(121, 85, 72), 2, true));
        ConvertLanhuage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConvertLanhuage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ConvertLanhuage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConvertLanhuageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConvertLanhuageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConvertLanhuageMouseExited(evt);
            }
        });

        ModifyLabel.setFont(new java.awt.Font("Consolas", 3, 32)); // NOI18N
        ModifyLabel.setForeground(new java.awt.Color(0, 66, 55));
        ModifyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ModifyLabel.setText("modify");
        ModifyLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(121, 85, 72), 2, true));
        ModifyLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModifyLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ModifyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifyLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ModifyLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ModifyLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConvertLanhuage, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModifyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(AddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(ConvertLanhuage, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(ModifyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
        );

        LeftScrollPane.setViewportView(LeftPanel);

        DifTextField.setEditable(false);
        DifTextField.setBackground(new java.awt.Color(47, 70, 81));
        DifTextField.setFont(new java.awt.Font("Monospaced", 3, 30)); // NOI18N
        DifTextField.setForeground(new java.awt.Color(2, 28, 28));
        DifTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DifTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 236), 2, true));

        FilterButton.setBackground(new java.awt.Color(41, 56, 64));
        FilterButton.setFont(new java.awt.Font("Consolas", 3, 30)); // NOI18N
        FilterButton.setForeground(new java.awt.Color(2, 35, 29));
        FilterButton.setText("Filter");
        FilterButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(109, 76, 65), 3, true));
        FilterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FilterButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        FilterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FilterButtonMouseClicked(evt);
            }
        });

        ModifyButton.setBackground(new java.awt.Color(41, 56, 64));
        ModifyButton.setFont(new java.awt.Font("Consolas", 3, 30)); // NOI18N
        ModifyButton.setForeground(new java.awt.Color(2, 35, 29));
        ModifyButton.setText("Modify");
        ModifyButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(109, 76, 65), 3, true));
        ModifyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModifyButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ModifyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifyButtonMouseClicked(evt);
            }
        });
        ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addComponent(ListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, Short.MAX_VALUE)
                .addComponent(TranslateButton)
                .addGap(50, 50, 50)
                .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(LanguageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(voicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addComponent(LeftScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(ModifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186)
                        .addComponent(FilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(309, 309, 309))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(DifTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SahmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Difinition_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(726, 726, 726))))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(voicLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(LanguageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TranslateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addComponent(Difinition_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SahmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DifTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(206, Short.MAX_VALUE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(ListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(LeftScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void CloseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseEntered
        CloseLabel.setBackground(Color.RED);
        CloseLabel.setOpaque(true);
    }//GEN-LAST:event_CloseLabelMouseEntered

    private void CloseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseExited
        CloseLabel.setBackground(null);
        CloseLabel.setOpaque(false);
    }//GEN-LAST:event_CloseLabelMouseExited

    private void MinusLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabelMouseClicked
        this.setState(DictionaryProject.ICONIFIED);
    }//GEN-LAST:event_MinusLabelMouseClicked

    private void MinusLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabelMouseEntered
        MinusLabel.setBackground(Color.LIGHT_GRAY);
        MinusLabel.setOpaque(true);
    }//GEN-LAST:event_MinusLabelMouseEntered

    private void MinusLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabelMouseExited
        MinusLabel.setBackground(null);
        MinusLabel.setOpaque(false);
    }//GEN-LAST:event_MinusLabelMouseExited

    private void TranslateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TranslateButtonMouseEntered
        TranslateButton.setBackground(Color.DARK_GRAY);
        TranslateButton.setOpaque(true);
    }//GEN-LAST:event_TranslateButtonMouseEntered

    private void TranslateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TranslateButtonMouseExited
        TranslateButton.setBackground(null);
        TranslateButton.setOpaque(false);
    }//GEN-LAST:event_TranslateButtonMouseExited

    private void AddLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLabelMouseEntered
        AddLabel.setBackground(new Color(121, 85, 72));
        AddLabel.setOpaque(true);
        Border b = BorderFactory.createLineBorder(new Color(109, 76, 65), 3, true);
        AddLabel.setBorder(b);
    }//GEN-LAST:event_AddLabelMouseEntered

    private void AddLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLabelMouseExited
        
        AddLabel.setBackground(null);
        AddLabel.setOpaque(false);
        Border b = BorderFactory.createLineBorder(new Color(121, 85, 72), 2, true);
        AddLabel.setBorder(b);
    }//GEN-LAST:event_AddLabelMouseExited

    private void ConvertLanhuageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConvertLanhuageMouseEntered
        ConvertLanhuage.setBackground(new Color(121, 85, 72));
        ConvertLanhuage.setOpaque(true);
        Border b = BorderFactory.createLineBorder(new Color(109, 76, 65), 3, true);
        ConvertLanhuage.setBorder(b);
    }//GEN-LAST:event_ConvertLanhuageMouseEntered

    private void ConvertLanhuageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConvertLanhuageMouseExited
        ConvertLanhuage.setBackground(null);
        ConvertLanhuage.setOpaque(false);
        Border b = BorderFactory.createLineBorder(new Color(121, 85, 72), 2, true);
        ConvertLanhuage.setBorder(b);
    }//GEN-LAST:event_ConvertLanhuageMouseExited

    private void ListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListButtonActionPerformed
          String s = "icons/Import_50px.PNG";
        ImageIcon i = new ImageIcon(s);
        Icon ic = new IconUIResource(i);
        ListButton.setIcon(ic);
        LeftScrollPane.setVisible(false);
    }//GEN-LAST:event_ListButtonActionPerformed

    private void ListButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListButtonMouseEntered
        String s = "icons/Menu_50px.PNG";
        ImageIcon i = new ImageIcon(s);
        Icon ic = new IconUIResource(i);
        ListButton.setIcon(ic);
        LeftScrollPane.setVisible(true);
    }//GEN-LAST:event_ListButtonMouseEntered

    private void ModifyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyLabelMouseClicked
        File f1 =  new File("ArabicWords.txt");
        try {
            FileReader fr1 = new FileReader(f1);
            BufferedReader bw1 = new BufferedReader(fr1);
            String data =  null ;
            while((data = bw1.readLine()) != null)
            {
               list.add(data);
                //if(data.equals(DifTextField.getText()))
                //{
                    result = data; 
                    System.out.println(result);
                  ModifyButton.setVisible(true);
                  //DifTextField.setEditable(true);
                  check = true;
                //}
            }
            
            bw1.close();
           //f1.delete();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_ModifyLabelMouseClicked

    private void ModifyLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyLabelMouseEntered
       ModifyLabel.setBackground(new Color(121, 85, 72));
        ModifyLabel.setOpaque(true);
        Border b = BorderFactory.createLineBorder(new Color(109, 76, 65), 3, true);
        ModifyLabel.setBorder(b);
    }//GEN-LAST:event_ModifyLabelMouseEntered

    private void ModifyLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyLabelMouseExited
         ModifyLabel.setBackground(null);
        ModifyLabel.setOpaque(false);
        Border b = BorderFactory.createLineBorder(new Color(121, 85, 72), 2, true);
        ModifyLabel.setBorder(b);
    }//GEN-LAST:event_ModifyLabelMouseExited

    private void TranslateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TranslateButtonActionPerformed
        File f1 = new File("EnglishWords.txt");
        File f2 = new File("ArabicWords.txt");
        int count = 0;
        int count1 = 0;
        boolean flag = false ;
        if(LanguageLabel.getText().equals("EN->AR"))
        {
                try {
                FileReader fr1 =  new FileReader(f1);
                FileReader fr2 =  new FileReader(f2);
                BufferedReader bf1 =  new BufferedReader(fr1);
                BufferedReader bf2 = new BufferedReader(fr2);
                String data = null;
                String result = null;
                while((data = bf1.readLine()) != null)
                {
                    count++;
                    if(data.equals(SearchTextField.getText()))
                    {
                        flag = true ;
                        break;
    //                    while((result = bf2.readLine())!= null)
    //                    {
    //                        count1++;
    //                        if(count == count1)
    //                        {
    //                            DifTextField.setText(result);
    //                        }
    //                    }
                    }
                }
                if(flag){
                    while((result = bf2.readLine()) != null)
                   {
                      count1++;
                      if(count == count1)
                      {
                           DifTextField.setText(result);
                      }

                   }
                }else
                {
                   DifTextField.setText("There is no word");
                }
                 bf1.close();
                 bf2.close();
            } catch (Exception e) {
                System.out.println(e);
            }
        }else if(LanguageLabel.getText().equals("AR->EN"))
        {
            try {
                FileReader fr1 =  new FileReader(f1);
                FileReader fr2 =  new FileReader(f2);
                BufferedReader bf1 =  new BufferedReader(fr1);
                BufferedReader bf2 = new BufferedReader(fr2);
                String data = null;
                String result = null;
                while((data = bf2.readLine()) != null)
                {
                    count++;
                    if(data.equals(SearchTextField.getText()))
                    {
                        flag = true ;
                        break;
    //                    while((result = bf2.readLine())!= null)
    //                    {
    //                        count1++;
    //                        if(count == count1)
    //                        {
    //                            DifTextField.setText(result);
    //                        }
    //                    }
                    }
                }
                if(flag){
                    while((result = bf1.readLine()) != null)
                   {
                      count1++;
                      if(count == count1)
                      {
                           DifTextField.setText(result);
                      }

                   }
                }else
                {
                   DifTextField.setText("There is no word");
                }
               bf1.close();
               bf2.close();
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_TranslateButtonActionPerformed

    private void AddLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLabelMouseClicked
       AddWord add = new AddWord();
       add.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_AddLabelMouseClicked

    private void voicLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voicLabelMouseClicked
        VoiceManager vm = VoiceManager.getInstance();
        Voice v = vm.getVoice("kevin16");
        v.allocate();
        v.speak(SearchTextField.getText());
    }//GEN-LAST:event_voicLabelMouseClicked

    private void ConvertLanhuageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConvertLanhuageMouseClicked
       if(LanguageLabel.getText().equals("EN->AR"))
       {
           LanguageLabel.setText("AR->EN");
           ConvertLanhuage.setText("EN->AR");
           DifTextField.setText("");
           SearchTextField.setText("");
       }else if(LanguageLabel.getText().equals("AR->EN"))
       {
           LanguageLabel.setText("EN->AR");
           ConvertLanhuage.setText("AR->EN");
           DifTextField.setText("");
           SearchTextField.setText("");
       }
    }//GEN-LAST:event_ConvertLanhuageMouseClicked

    private void FilterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FilterButtonMouseClicked
       SearchTextField.setText("");
       DifTextField.setText("");
    }//GEN-LAST:event_FilterButtonMouseClicked

    private void ModifyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyButtonMouseClicked
        for(int i = 0 ;i <list.size() ; i++)
        {
            if(list.get(i).equals(result))
            {
                list.remove(i);
                list.add(i,DifTextField.getText());
            }
        }
        
        File f =  new File("ArabicWords.txt" );
        try {
            FileWriter fw =  new FileWriter(f , true);
            BufferedWriter bw =  new BufferedWriter(fw);
            for(String data : list)
            {
                bw.write(data);
                bw.newLine();
            }
            JOptionPane.showMessageDialog(null, "Successfulyy modified ^_^");
            bw.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ModifyButtonMouseClicked

    private void ModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        DictionaryProject dc = new DictionaryProject();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dc.setVisible(true);
                dc.LeftScrollPane.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddLabel;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JLabel ConvertLanhuage;
    private javax.swing.JLabel Dictionary;
    private javax.swing.JTextField DifTextField;
    private javax.swing.JLabel Difinition_Label;
    private javax.swing.JButton FilterButton;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel LanguageLabel;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JScrollPane LeftScrollPane;
    private javax.swing.JButton ListButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel MinusLabel;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JLabel ModifyLabel;
    private javax.swing.JLabel SahmLabel;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JButton TranslateButton;
    private javax.swing.JLabel voicLabel;
    // End of variables declaration//GEN-END:variables
}
