/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package task4;

import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;

/**
 *
 * @author AhmedTalal
 */
public class Modify extends javax.swing.JFrame {

    /**
     * Creates new form Modify
     */
    public Modify() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        CloseLabel = new javax.swing.JLabel();
        MinusLabel = new javax.swing.JLabel();
        Dictionary = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        TranslateButton = new javax.swing.JButton();
        SearchTextField = new javax.swing.JTextField();
        LanguageLabel = new javax.swing.JLabel();
        voicLabel = new javax.swing.JLabel();
        DifTextField = new javax.swing.JTextField();
        Difinition_Label = new javax.swing.JLabel();
        SahmLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        HeaderPanel.setBackground(new java.awt.Color(109, 130, 140));

        CloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLabel.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Xbox X_30px_1.png")); // NOI18N
        CloseLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseLabelMouseExited(evt);
            }
        });

        MinusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinusLabel.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Minus_30px_1.png")); // NOI18N
        MinusLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinusLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinusLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinusLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinusLabelMouseExited(evt);
            }
        });

        Dictionary.setFont(new java.awt.Font("Consolas", 3, 30)); // NOI18N
        Dictionary.setForeground(new java.awt.Color(0, 77, 64));
        Dictionary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dictionary.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Google Translate_50px.png")); // NOI18N
        Dictionary.setText("Dictionary");
        Dictionary.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addComponent(Dictionary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CloseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CloseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MinusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Dictionary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        MainPanel.setBackground(new java.awt.Color(69, 90, 100));

        TranslateButton.setBackground(new java.awt.Color(41, 56, 64));
        TranslateButton.setFont(new java.awt.Font("Consolas", 3, 30)); // NOI18N
        TranslateButton.setForeground(new java.awt.Color(2, 35, 29));
        TranslateButton.setText("translate");
        TranslateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TranslateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TranslateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TranslateButtonMouseExited(evt);
            }
        });
        TranslateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TranslateButtonActionPerformed(evt);
            }
        });

        SearchTextField.setBackground(new java.awt.Color(60, 82, 92));
        SearchTextField.setFont(new java.awt.Font("Monospaced", 3, 30)); // NOI18N
        SearchTextField.setForeground(new java.awt.Color(2, 28, 28));
        SearchTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 236), 2, true));

        LanguageLabel.setFont(new java.awt.Font("Consolas", 3, 30)); // NOI18N
        LanguageLabel.setForeground(new java.awt.Color(0, 51, 51));
        LanguageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LanguageLabel.setText("EN->AR");
        LanguageLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(78, 52, 46), 2, true));

        voicLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voicLabel.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Microphone_50px_1.png")); // NOI18N
        voicLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(78, 52, 46), 2, true));
        voicLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voicLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voicLabelMouseClicked(evt);
            }
        });

        DifTextField.setBackground(new java.awt.Color(60, 82, 92));
        DifTextField.setFont(new java.awt.Font("Monospaced", 3, 30)); // NOI18N
        DifTextField.setForeground(new java.awt.Color(2, 28, 28));
        DifTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DifTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 236), 2, true));

        Difinition_Label.setFont(new java.awt.Font("Consolas", 3, 30)); // NOI18N
        Difinition_Label.setForeground(new java.awt.Color(2, 35, 29));
        Difinition_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Difinition_Label.setText("Definition");
        Difinition_Label.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(78, 52, 46), 2, true));

        SahmLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SahmLabel.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Logout Rounded Down_25px.png")); // NOI18N

        jButton1.setBackground(new java.awt.Color(41, 56, 64));
        jButton1.setFont(new java.awt.Font("Consolas", 3, 30)); // NOI18N
        jButton1.setForeground(new java.awt.Color(2, 35, 29));
        jButton1.setText("Filter");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(109, 76, 65), 2, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(41, 56, 64));
        jButton2.setFont(new java.awt.Font("Consolas", 3, 30)); // NOI18N
        jButton2.setForeground(new java.awt.Color(2, 35, 29));
        jButton2.setText("Filter");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(109, 76, 65), 2, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(309, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(TranslateButton)
                        .addGap(50, 50, 50)
                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(LanguageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(voicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                            .addGap(207, 207, 207)
                            .addComponent(DifTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(214, 214, 214))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                    .addComponent(Difinition_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(737, 737, 737))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                    .addComponent(SahmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(730, 730, 730))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(220, 220, 220)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(310, 310, 310))))))
                .addGap(28, 28, 28))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(voicLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LanguageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TranslateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(Difinition_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SahmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(DifTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void CloseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseEntered
        CloseLabel.setBackground(Color.RED);
        CloseLabel.setOpaque(true);
    }//GEN-LAST:event_CloseLabelMouseEntered

    private void CloseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseExited
        CloseLabel.setBackground(null);
        CloseLabel.setOpaque(false);
    }//GEN-LAST:event_CloseLabelMouseExited

    private void MinusLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabelMouseClicked
        this.setState(DictionaryProject.ICONIFIED);
    }//GEN-LAST:event_MinusLabelMouseClicked

    private void MinusLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabelMouseEntered
        MinusLabel.setBackground(Color.LIGHT_GRAY);
        MinusLabel.setOpaque(true);
    }//GEN-LAST:event_MinusLabelMouseEntered

    private void MinusLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabelMouseExited
        MinusLabel.setBackground(null);
        MinusLabel.setOpaque(false);
    }//GEN-LAST:event_MinusLabelMouseExited

    private void TranslateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TranslateButtonMouseEntered
        TranslateButton.setBackground(Color.DARK_GRAY);
        TranslateButton.setOpaque(true);
    }//GEN-LAST:event_TranslateButtonMouseEntered

    private void TranslateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TranslateButtonMouseExited
        TranslateButton.setBackground(null);
        TranslateButton.setOpaque(false);
    }//GEN-LAST:event_TranslateButtonMouseExited

    private void TranslateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TranslateButtonActionPerformed
        File f1 = new File("EnglishWords.txt");
        File f2 = new File("ArabicWords.txt");
        int count = 0;
        int count1 = 0;
        boolean flag = false ;
            try {
                FileReader fr1 =  new FileReader(f1);
                FileReader fr2 =  new FileReader(f2);
                BufferedReader bf1 =  new BufferedReader(fr1);
                BufferedReader bf2 = new BufferedReader(fr2);
                String data = null;
                String result = null;
                while((data = bf1.readLine()) != null)
                {
                    count++;
                    if(data.equals(SearchTextField.getText()))
                    {
                        flag = true ;
                        break;
                        //                    while((result = bf2.readLine())!= null)
                        //                    {
                            //                        count1++;
                            //                        if(count == count1)
                            //                        {
                                //                            DifTextField.setText(result);
                                //                        }
                            //                    }
                    }
                }
                if(flag){
                    while((result = bf2.readLine()) != null)
                    {
                        count1++;
                        if(count == count1)
                        {
                            DifTextField.setText(result);
                        }

                    }
                }else
                {
                    DifTextField.setText("There is no word");
                }

            } catch (Exception e) {
                System.out.println(e);
            }
    }//GEN-LAST:event_TranslateButtonActionPerformed

    private void voicLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voicLabelMouseClicked
        VoiceManager vm = VoiceManager.getInstance();
        Voice v = vm.getVoice("kevin16");
        v.allocate();
        v.speak(SearchTextField.getText());
    }//GEN-LAST:event_voicLabelMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        SearchTextField.setText("");
        DifTextField.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JLabel Dictionary;
    private javax.swing.JTextField DifTextField;
    private javax.swing.JLabel Difinition_Label;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel LanguageLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel MinusLabel;
    private javax.swing.JLabel SahmLabel;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JButton TranslateButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel voicLabel;
    // End of variables declaration//GEN-END:variables
}
