/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package task4;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author AhmedTalal
 */
public class printDate extends javax.swing.JFrame {

    /**
     * Creates new form printDate
     */
    public printDate() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        CloseLabel = new javax.swing.JLabel();
        MinusLabel = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        pathTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        printDtaeTextArea = new javax.swing.JTextArea();
        printButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LineTextField1 = new javax.swing.JTextField();
        ChooseFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setUndecorated(true);

        HeaderPanel.setBackground(new java.awt.Color(0, 105, 92));

        CloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLabel.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Xbox X_30px_1.png")); // NOI18N
        CloseLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseLabelMouseExited(evt);
            }
        });

        MinusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinusLabel.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Minus_30px_1.png")); // NOI18N
        MinusLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinusLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinusLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinusLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinusLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MinusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CloseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CloseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
            .addComponent(MinusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MainPanel.setBackground(new java.awt.Color(5, 121, 111));

        pathTextField.setBackground(new java.awt.Color(0, 105, 92));
        pathTextField.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        pathTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 77, 64), 3, true));

        jLabel1.setFont(new java.awt.Font("Consolas", 3, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 70, 62));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter the path :");

        printDtaeTextArea.setEditable(false);
        printDtaeTextArea.setBackground(new java.awt.Color(0, 105, 92));
        printDtaeTextArea.setColumns(20);
        printDtaeTextArea.setFont(new java.awt.Font("Consolas", 3, 25)); // NOI18N
        printDtaeTextArea.setRows(5);
        jScrollPane1.setViewportView(printDtaeTextArea);

        printButton.setBackground(new java.awt.Color(0, 91, 79));
        printButton.setFont(new java.awt.Font("Consolas", 1, 25)); // NOI18N
        printButton.setForeground(new java.awt.Color(6, 70, 62));
        printButton.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Print_50px.png")); // NOI18N
        printButton.setText("print");
        printButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        printButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        printButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printButtonMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 3, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(6, 70, 62));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter the line :");

        LineTextField1.setBackground(new java.awt.Color(0, 105, 92));
        LineTextField1.setFont(new java.awt.Font("Consolas", 3, 25)); // NOI18N
        LineTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 77, 64), 3, true));

        ChooseFile.setBackground(new java.awt.Color(0, 77, 64));
        ChooseFile.setIcon(new javax.swing.ImageIcon("E:\\MyWork_coding\\NetBeansProjects\\task4\\icons\\Folder_48px.png")); // NOI18N
        ChooseFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChooseFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ChooseFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChooseFileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChooseFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChooseFileMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(444, 444, 444))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(459, 459, 459)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(LineTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(ChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(42, 42, 42))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LineTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void CloseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseEntered
        CloseLabel.setBackground(Color.RED);
        CloseLabel.setOpaque(true);
    }//GEN-LAST:event_CloseLabelMouseEntered

    private void CloseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseExited
        CloseLabel.setBackground(null);
        CloseLabel.setOpaque(false);
    }//GEN-LAST:event_CloseLabelMouseExited

    private void MinusLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabelMouseClicked
        this.setState(printDate.ICONIFIED);
    }//GEN-LAST:event_MinusLabelMouseClicked

    private void MinusLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabelMouseEntered
        MinusLabel.setBackground(Color.GRAY);
        MinusLabel.setOpaque(true);
    }//GEN-LAST:event_MinusLabelMouseEntered

    private void MinusLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabelMouseExited
        MinusLabel.setBackground(null);
        MinusLabel.setOpaque(false);
    }//GEN-LAST:event_MinusLabelMouseExited

    private void printButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printButtonMouseEntered
        printButton.setBackground(Color.DARK_GRAY);
        printButton.setOpaque(true);
        Border b = BorderFactory.createLineBorder(Color.DARK_GRAY, 4, true);
        printButton.setBorder(b);
    }//GEN-LAST:event_printButtonMouseEntered

    private void printButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printButtonMouseExited
        printButton.setBackground(null);
        printButton.setOpaque(false);
        printButton.setBorder(null);
    }//GEN-LAST:event_printButtonMouseExited

    private void printButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printButtonMouseClicked
        File f = new File(pathTextField.getText());
        int count = 0;
        try {
            FileReader fr =  new FileReader(f);
            BufferedReader bf = new BufferedReader(fr);
            String  data  = null;
            while((data  = bf.readLine()) != null)
            {
                count++;
                if(count == Integer.valueOf(LineTextField1.getText()))
                {
                    printDtaeTextArea.setText("line " + count  + " : " + data);
                }
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "File not found", "Error", 3);
        }
        
    }//GEN-LAST:event_printButtonMouseClicked

    private void ChooseFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseFileMouseEntered
       ChooseFile.setBackground(Color.DARK_GRAY);
        ChooseFile.setOpaque(true);
        Border b = BorderFactory.createLineBorder(Color.DARK_GRAY, 2, true);
        ChooseFile.setBorder(b);
    }//GEN-LAST:event_ChooseFileMouseEntered

    private void ChooseFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseFileMouseExited
        ChooseFile.setBackground(null);
        ChooseFile.setOpaque(false);
        ChooseFile.setBorder(null);
    }//GEN-LAST:event_ChooseFileMouseExited

    private void ChooseFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseFileMouseClicked
        JFileChooser choose = new JFileChooser();
        choose.showOpenDialog(null);
        File f = choose.getSelectedFile();
        String path =  f.getAbsolutePath();
        pathTextField.setText(path);
    }//GEN-LAST:event_ChooseFileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printDate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChooseFile;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JTextField LineTextField1;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel MinusLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JButton printButton;
    private javax.swing.JTextArea printDtaeTextArea;
    // End of variables declaration//GEN-END:variables
}
